<div><h3 id="selectedOptionDisplay" style="display: none;">Seller :</h3></div><script>
    
    var selectedOption = sessionStorage.getItem('selected_option');
    console.log(selectedOption);

    
    if (selectedOption) {
        document.getElementById('selectedOptionDisplay').textContent += selectedOption;
        document.getElementById('selectedOptionDisplay').style.display = 'block';
    } else {
        console.log("No option selected");
    }</script>